const people = {
  dentists: [
    {
      id: 1,
      first_name: "Jewelle",
      last_name: "Lightowler",
      email: "jlightowler0@disqus.com",
      telnr: "4374002221",
      isSick: false,
    },
    {
      id: 2,
      first_name: "Arlie",
      last_name: "Hookes",
      email: "ahookes1@usatoday.com",
      telnr: "6725821315",
      isSick: false,
    },
    {
      id: 3,
      first_name: "Priscilla",
      last_name: "Aumerle",
      email: "paumerle2@wunderground.com",
      telnr: "2611423742",
      isSick: false,
    },
    {
      id: 4,
      first_name: "Gael",
      last_name: "Dempster",
      email: "gdempster3@ucoz.ru",
      telnr: "7491487971",
      isSick: false,
    },
  ],
  assistants: [
    {
      id: 1,
      first_name: "Welbie",
      last_name: "Heeps",
      email: "wheeps0@trellian.com",
      telnr: "3609557087",
      isSick: false,
    },
    {
      id: 2,
      first_name: "Gabriella",
      last_name: "Fairnington",
      email: "gfairnington1@paginegialle.it",
      telnr: "4405851109",
      isSick: false,
    },
  ],
  clients: [
    {
      id: 1,
      first_name: "Kissiah",
      last_name: "Weerdenburg",
      email: "kweerdenburg0@toplist.cz",
      telnr: "2224675986",
      birthdate: "29-11-1955",
      isSick: false,
    },
    {
      id: 2,
      first_name: "Daloris",
      last_name: "Perrott",
      email: "dperrott1@boston.com",
      telnr: "8652601268",
      birthdate: "30-04-1999",
      isSick: false,
    },
    {
      id: 3,
      first_name: "Dona",
      last_name: "Colum",
      email: "dcolum2@forbes.com",
      telnr: "1449760719",
      birthdate: "30-04-1939",
      isSick: false,
    },
    {
      id: 4,
      first_name: "Darleen",
      last_name: "Moxley",
      email: "dmoxley3@wp.com",
      telnr: "9947315633",
      birthdate: "05-08-1997",
      isSick: false,
    },
    {
      id: 5,
      first_name: "Gale",
      last_name: "Van Der Straaten",
      email: "gvanderstraaten4@who.int",
      telnr: "9799222779",
      birthdate: "29-07-2006",
      isSick: false,
    },
    {
      id: 6,
      first_name: "Nell",
      last_name: "Viggers",
      email: "nviggers5@dion.ne.jp",
      telnr: "2943131490",
      birthdate: "03-10-1965",
      isSick: false,
    },
    {
      id: 7,
      first_name: "Neysa",
      last_name: "Basset",
      email: "nbasset6@acquirethisname.com",
      telnr: "5194577349",
      birthdate: "23-01-2022",
      isSick: false,
    },
    {
      id: 8,
      first_name: "Janenna",
      last_name: "Maskrey",
      email: "jmaskrey7@arstechnica.com",
      telnr: "7292292935",
      birthdate: "25-11-2001",
      isSick: false,
    },
    {
      id: 9,
      first_name: "Terrence",
      last_name: "Woolhouse",
      email: "twoolhouse8@dailymotion.com",
      telnr: "9077819870",
      birthdate: "03-04-1985",
      isSick: false,
    },
    {
      id: 10,
      first_name: "Lonnie",
      last_name: "Coultass",
      email: "lcoultass9@utexas.edu",
      telnr: "2089768429",
      birthdate: "21-09-2005",
      isSick: false,
    },
    {
      id: 11,
      first_name: "Bord",
      last_name: "Ghidoli",
      email: "bghidolia@zimbio.com",
      telnr: "6325629056",
      birthdate: "14-09-1955",
      isSick: false,
    },
    {
      id: 12,
      first_name: "Gasparo",
      last_name: "Thoma",
      email: "gthomab@livejournal.com",
      telnr: "7844193482",
      birthdate: "20-01-1958",
      isSick: false,
    },
    {
      id: 13,
      first_name: "Addie",
      last_name: "Fancet",
      email: "afancetc@bizjournals.com",
      telnr: "8426324563",
      birthdate: "28-04-2014",
      isSick: false,
    },
    {
      id: 14,
      first_name: "Aldrich",
      last_name: "Longea",
      email: "alongead@ycombinator.com",
      telnr: "5296930225",
      birthdate: "29-05-2000",
      isSick: false,
    },
    {
      id: 15,
      first_name: "Cally",
      last_name: "Braid",
      email: "cbraide@diigo.com",
      telnr: "8834827894",
      birthdate: "04-12-2020",
      isSick: false,
    },
    {
      id: 16,
      first_name: "Teresa",
      last_name: "Salery",
      email: "tsaleryf@so-net.ne.jp",
      telnr: "9753795868",
      birthdate: "16-08-1974",
      isSick: false,
    },
    {
      id: 17,
      first_name: "Myranda",
      last_name: "Castellan",
      email: "mcastellang@tumblr.com",
      telnr: "6386427593",
      birthdate: "30-10-2001",
      isSick: false,
    },
    {
      id: 18,
      first_name: "Audra",
      last_name: "Klementz",
      email: "aklementzh@hugedomains.com",
      telnr: "1701779853",
      birthdate: "08-09-1955",
      isSick: false,
    },
    {
      id: 19,
      first_name: "Hy",
      last_name: "Tomas",
      email: "htomasi@boston.com",
      telnr: "7323572041",
      birthdate: "21-01-2007",
      isSick: false,
    },
    {
      id: 20,
      first_name: "Gregory",
      last_name: "Grimmert",
      email: "ggrimmertj@about.me",
      telnr: "4261760832",
      birthdate: "19-08-1950",
      isSick: false,
    },
    {
      id: 21,
      first_name: "Araldo",
      last_name: "Antognetti",
      email: "aantognettik@naver.com",
      telnr: "1249896104",
      birthdate: "17-12-2008",
      isSick: false,
    },
    {
      id: 22,
      first_name: "Chaim",
      last_name: "Ellif",
      email: "cellifl@cbc.ca",
      telnr: "2578425926",
      birthdate: "16-08-1988",
      isSick: false,
    },
    {
      id: 23,
      first_name: "Ileana",
      last_name: "Kidds",
      email: "ikiddsm@xrea.com",
      telnr: "6748480240",
      birthdate: "20-10-1984",
      isSick: false,
    },
    {
      id: 24,
      first_name: "Emelen",
      last_name: "Dinesen",
      email: "edinesenn@nyu.edu",
      telnr: "4785411630",
      birthdate: "31-01-1967",
      isSick: false,
    },
    {
      id: 25,
      first_name: "Raynard",
      last_name: "Savaage",
      email: "rsavaageo@amazon.de",
      telnr: "3673927436",
      birthdate: "23-06-1950",
      isSick: false,
    },
    {
      id: 26,
      first_name: "Megan",
      last_name: "Knok",
      email: "mknokp@domainmarket.com",
      telnr: "9407675927",
      birthdate: "05-01-1975",
      isSick: false,
    },
    {
      id: 27,
      first_name: "Gloriane",
      last_name: "Holsey",
      email: "gholseyq@issuu.com",
      telnr: "8825127480",
      birthdate: "11-09-1942",
      isSick: false,
    },
    {
      id: 28,
      first_name: "Dara",
      last_name: "Clissold",
      email: "dclissoldr@friendfeed.com",
      telnr: "2013056237",
      birthdate: "05-04-2017",
      isSick: false,
    },
    {
      id: 29,
      first_name: "Anabella",
      last_name: "Breyt",
      email: "abreyts@noaa.gov",
      telnr: "3345833823",
      birthdate: "03-12-1988",
      isSick: false,
    },
    {
      id: 30,
      first_name: "Lanny",
      last_name: "Dennert",
      email: "ldennertt@unc.edu",
      telnr: "5368644378",
      birthdate: "21-01-1961",
      isSick: false,
    },
    {
      id: 31,
      first_name: "Nico",
      last_name: "O'Brallaghan",
      email: "nobrallaghanu@xing.com",
      telnr: "4054753776",
      birthdate: "12-01-1935",
      isSick: false,
    },
    {
      id: 32,
      first_name: "Brynna",
      last_name: "Cayette",
      email: "bcayettev@ebay.co.uk",
      telnr: "5792375866",
      birthdate: "27-03-2007",
      isSick: false,
    },
    {
      id: 33,
      first_name: "Anstice",
      last_name: "Sachno",
      email: "asachnow@diigo.com",
      telnr: "2208052981",
      birthdate: "21-11-2000",
      isSick: false,
    },
    {
      id: 34,
      first_name: "Minne",
      last_name: "Bingley",
      email: "mbingleyx@ed.gov",
      telnr: "3852031513",
      birthdate: "04-05-2005",
      isSick: false,
    },
    {
      id: 35,
      first_name: "Archaimbaud",
      last_name: "Babbs",
      email: "ababbsy@pagesperso-orange.fr",
      telnr: "5274086586",
      birthdate: "25-11-1973",
      isSick: false,
    },
    {
      id: 36,
      first_name: "Stanley",
      last_name: "Cazalet",
      email: "scazaletz@berkeley.edu",
      telnr: "2842008842",
      birthdate: "09-09-1977",
      isSick: false,
    },
    {
      id: 37,
      first_name: "Josiah",
      last_name: "McMeekin",
      email: "jmcmeekin10@discuz.net",
      telnr: "6161758559",
      birthdate: "28-12-1998",
      isSick: false,
    },
    {
      id: 38,
      first_name: "Aprilette",
      last_name: "Vernazza",
      email: "avernazza11@bluehost.com",
      telnr: "1784571197",
      birthdate: "24-10-1942",
      isSick: false,
    },
    {
      id: 39,
      first_name: "Randolph",
      last_name: "Bewshea",
      email: "rbewshea12@cmu.edu",
      telnr: "5329773509",
      birthdate: "16-07-1944",
      isSick: false,
    },
    {
      id: 40,
      first_name: "Sybille",
      last_name: "Holt",
      email: "sholt13@hibu.com",
      telnr: "6844840813",
      birthdate: "25-02-1995",
      isSick: false,
    },
    {
      id: 41,
      first_name: "Bernadette",
      last_name: "Janssens",
      email: "bjanssens14@xrea.com",
      telnr: "3332164118",
      birthdate: "11-09-1987",
      isSick: false,
    },
    {
      id: 42,
      first_name: "Samuele",
      last_name: "Croxall",
      email: "scroxall15@state.gov",
      telnr: "4578103370",
      birthdate: "03-10-1994",
      isSick: false,
    },
    {
      id: 43,
      first_name: "Alphard",
      last_name: "Queenborough",
      email: "aqueenborough16@unicef.org",
      telnr: "6461381400",
      birthdate: "25-02-2018",
      isSick: false,
    },
    {
      id: 44,
      first_name: "Katha",
      last_name: "Gherardini",
      email: "kgherardini17@360.cn",
      telnr: "9886083707",
      birthdate: "02-07-1973",
      isSick: false,
    },
    {
      id: 45,
      first_name: "Dorthea",
      last_name: "Segrave",
      email: "dsegrave18@walmart.com",
      telnr: "5823332388",
      birthdate: "21-11-2013",
      isSick: false,
    },
    {
      id: 46,
      first_name: "Gretta",
      last_name: "Zelake",
      email: "gzelake19@istockphoto.com",
      telnr: "6622811125",
      birthdate: "29-01-1977",
      isSick: false,
    },
    {
      id: 47,
      first_name: "Saba",
      last_name: "Wanley",
      email: "swanley1a@people.com.cn",
      telnr: "9198964572",
      birthdate: "23-01-2020",
      isSick: false,
    },
    {
      id: 48,
      first_name: "Ealasaid",
      last_name: "Shearmer",
      email: "eshearmer1b@ft.com",
      telnr: "8209406933",
      birthdate: "20-02-1967",
      isSick: false,
    },
    {
      id: 49,
      first_name: "Faydra",
      last_name: "Coulthard",
      email: "fcoulthard1c@sitemeter.com",
      telnr: "6067866429",
      birthdate: "16-10-1975",
      isSick: false,
    },
    {
      id: 50,
      first_name: "Patten",
      last_name: "Canacott",
      email: "pcanacott1d@state.tx.us",
      telnr: "4595434134",
      birthdate: "08-11-1998",
      isSick: false,
    },
  ],
};

export default people;
